learn_django/learn_django/urls.py
from django.contrib import admin
from django.urls import path, include


from learn_django.otusPlus.views.views import index_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('myblog.urls')),
    path('otus/', index_view),
]

learn_django/myblog/urls.py
from django.urls import path


from .views import index_view

app_name = 'myblog'

urlpatterns = [
    path('', index_view, name='index'),
]

learn_django/otusPlus/urls.py
from django.urls import path


from learn_django.otusPlus.views.views import index_view
import learn_django.otusPlus.views.cb_views as class_based_views
# from .views.cb_views import

app_name = 'otusPlus'

urlpatterns = [
    path('', index_view, name='index'),
    # Class based views
    # path('cb_course_list/', class_based_views.CourseListView.as_view()),
    path('cb_course_create/', class_based_views.CreateCourseView.as_view()),
    # path('cb_course_detail/<int:pk>', class_based_views.CourseDetailView.as_view()),
    # path('cb_course_list/', class_based_views.CourseListView.as_view()),
]

learn_django/myblog/models.py
from django.db import models


class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name


class Article(models.Model):

    TTR_L_1 = 1
    TTR_1_5 = 2
    TTR_5_15 = 3
    TTR_15_30 = 4
    TTR_G_30 = 5

    TIME_TO_READ = (
        (TTR_L_1, '< 1 min'),
        (TTR_1_5, '1 - 5 min'),
        (TTR_5_15, '5 - 15 min'),
        (TTR_15_30, '15 - 30 min'),
        (TTR_G_30, '> 30 min'),
    )

    title = models.CharField(max_length=254)
    text = models.TextField()
    time_to_read = models.IntegerField(choices=TIME_TO_READ)
    ts_last_changed = models.DateTimeField(auto_now=True)
    ts_created = models.DateTimeField(auto_now_add=True)

    author = models.ForeignKey(Author, on_delete=models.PROTECT)

    def __str__(self):
        return self.title

learn_django/otusPlus/models.py
from django.db import models
from django.db.models import PROTECT, SET_NULL


class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name


class Document(models.Model):

    TYPE_OF_DOC = (
        (1, 'article'),
        (2, 'book'),
        (3, 'scan'),
        (4, 'plan'),
        (5, 'scratch'),
    )

    TIME_TO_READ = (
        (1, '< 1 min'),
        (2, '1 - 5 min'),
        (3, '5 - 10 min'),
        (4, '10 - 15 min'),
        (5, '> 15 min'),
    )

    title = models.CharField(max_length=254)
    text = models.TextField()
    type_of_doc = models.IntegerField(choices=TYPE_OF_DOC)
    time_to_read = models.IntegerField(choices=TIME_TO_READ)
    ts_last_changed = models.DateTimeField(auto_now=True)
    ts_created = models.DateTimeField(auto_now_add=True)

    author = models.ForeignKey(Author, on_delete=models.PROTECT)

    def __str__(self):
        return self.title


class Teacher(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name


class Student(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    courses = models.ManyToManyField('Course')

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name


class Course(models.Model):

    WHAT_TO_LEARN = (
        (1, 'CSS'),
        (2, 'HTML'),
        (3, 'JavaScript'),
        (4, 'Python'),
        (5, 'C++'),
    )

    title = models.CharField(max_length=100)
    what_to_learn = models.IntegerField(choices=WHAT_TO_LEARN)
    teacher = models.ForeignKey(Teacher, on_delete=SET_NULL, null=True)
    students = models.ManyToManyField(Student)

    def __str__(self):
        return self.title


class Lesson(models.Model):
    theme_of_lesson = models.CharField(max_length=100)
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    date_time_of_lesson = models.DateTimeField()
    teacher = models.ForeignKey(Teacher, on_delete=models.PROTECT)

    def __str__(self):
        return self.theme_of_lesson


class Calendar(models.Model):
    date = models.DateField()
    time = models.TimeField()

learn_django/otusPlus/forms.py
from django import forms
from .models import Author, Course, Teacher, Document, Student, Lesson, Calendar


class CourseSimpleForm(forms.Form):
    title = forms.CharField()
    what_to_learn = forms.ChoiceField(queryset=Course.objects.all(), label="WHAT_TO_LEARN")
    teacher = forms.ChoiceField(queryset=Teacher.objects.all(),label="Teacher")


class TeacherSimpleForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()


class StudentSimpleForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    course = forms.ChoiceField(queryset=Course.objects.all(), label="Course")

learn_django/myblog/views.py
from django.shortcuts import render

from .models import Author, Article


def index_view(request):
    article = Article.objects.get(pk=3)
    context = {
        'foo': 'bar',
        'article': article,
        'all_articles': Article.objects.all(),
        'all_B_authors': Author.objects.filter(first_name__startswith='B')
    }
    return render(request, 'myblog/index.html', context=context)

learn_django/otusPlus/views.py
from django.http import HttpResponse
from django.shortcuts import render
from datetime import datetime

from .models import Author, Document, Course, Student, Teacher, Lesson


def index_view(request):
    # return HttpResponse('<h1>Hello, OtusPlus index!</h1>')
    right_now = datetime.now()
    document = Document.objects.get(pk=1)
    context = {
        'foo': 'bar',
        'document': document,
        'all_docs': Document.objects.all(),
        'all_students': Student.objects.all(),
        'all_courses': Course.objects.all(),
        'all_teachers': Teacher.objects.all(),
        'all_lessons': Lesson.objects.all(),
        'hot_lessons': Lesson.objects.all()

    }
    return render(request, 'otusPlus/index.html', context=context)

learn_django/otusPlus/views/cb_views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView, CreateView, DetailView, YearArchiveView
from django.views.generic.base import View
from django.views.generic.list import ListView

from learn_django.otusPlus.forms import forms, CourseSimpleForm, TeacherSimpleForm, StudentSimpleForm
from learn_django.otusPlus.models import Course, Student, Lesson, Document


class CreateCourseView(View):
    form = forms.CourseSimpleForm

    def get(self, request):
        form = self.form()
        return render(request, 'create_course.html', context={"form": form})

    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            Course.objects.create(**form.cleaned_data)
        return render(request, 'create_course.html', context={"form": form})


class CreateStudentView(View):

    form = StudentSimpleForm

    def get(self, request):
        form = self.form()
        return render(request, 'create_student.html', context={"form": form})

    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            form.save()
        return render(request, 'create_student.html', context={"form": form})

learn_django/otusPlus/views/views.py
from django.http import HttpResponse
from django.shortcuts import render
from datetime import datetime

from learn_django.otusPlus.models import Author, Document, Course, Student, Teacher, Lesson


def index_view(request):
    right_now = datetime.now()
    document = Document.objects.get(pk=1)
    context = {
        'foo': 'bar',
        'document': document,
        'all_docs': Document.objects.all(),
        'all_students': Student.objects.all(),
        'all_courses': Course.objects.all(),
        'all_teachers': Teacher.objects.all(),
        'all_lessons': Lesson.objects.all(),
        'hot_lessons': Lesson.objects.all()

    }
    return render(request, 'index.html', context=context)

learn_django/myblog/templates/myblog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
<div>
    <h1>Hello, Django blog index!</h1>
    <ul>
        <li>foo: {{ foo }}</li>
        <li>__________</li>
        <li>Article: #{{ article.id }}
            with title {{ article.title }}
            with text {{ article.text }}
        </li>
        <li>
            Article TTR choices:
            <ul>
                {% for key, value in article.TIME_TO_READ %}
                <li><code>{{ key }} : {{ value }}</code></li>
                {% endfor %}
            </ul>
        </li>
        <li>
            Article is {% if article.time_to_read < article.TTR_5_15 %} not {% endif %} very long.
        </li>
    </ul>
    <hr>
    <div>
        This page url: {% url 'myblog:index' %}
    </div>
    <hr>
    <h3>Articles:</h3>
    <ul>
        {% for article in all_articles %}
            <li>
                <div>
                    Article #{{ article.id }}
                    with title {{ article.title }}
                </div>
                <div>
                    published: {{ article.ts_created }}
                </div>
                <div>
                    by {{ article.author }}
                </div>
            </li>
        {% endfor %}
    </ul>
    <hr>
    <h3>All 'B' authors :</h3>
    <ul>
        {% for author in all_B_authors %}
            <li>
                <div>
                    Author #{{ author.id }}
                    with full name {{ author.full_name }}
                </div>
                <div>
                    has these articles:
                    <ul>
                        {% for article in author.article_set.all %}
                        <li>
                            <div>
                                Article #{{ article.id }}
                                with title {{ article.title }}
                            </div>
                            <div>
                                published: {{ article.ts_created }}
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </li>
        {% endfor %}
    </ul>

</div>
</body>
</html>

learn_django/otusPlus/templates/otusPlus/all_courses.html
{% extends 'base.html' %}

{% block title %} Все курсы {% endblock title %}

{% block content %}

    <h1> Все курсы </h1>
    <table style="border: 1px solid">
        <tr style="border: 1px solid">
            <th style="border: 1px solid">Наименование курса</th>
            <th style="border: 1px solid">Специфика курса</th>
            <th style="border: 1px solid">Преподаватель</th>
        </tr>
    {% for course in courses %}
        <tr style="border: 1px solid">
            <td style="border: 1px solid"> {{ course.title }} </td>
            <td style="border: 1px solid"> {{ course.what_to_learn }}</td>
            <td style="border: 1px solid"> {{ course.teacher }}</td>
        </tr>
    {% endfor %}
     </table>

{% endblock content %}

learn_django/otusPlus/templates/otusPlus/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>
        {% block title %}
        {{ page_title | default:"Untitled Page" }}
        {% endblock title %}
    </title>
</head>
<body>
    {% block content %}
    <p>Placeholder text in base template. Replace with page content.</p>
    {% endblock content %}
</body>
</html>

learn_django/otusPlus/templates/otusPlus/create_course.html
{% extends 'base.html' %}

{% block title %} Create course {% endblock title %}

{% block content %}

    <h1> Create course </h1>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>

{% endblock content %}

learn_django/otusPlus/templates/otusPlus/create_student.html
{% extends 'base.html' %}

{% block title %} Create student {% endblock title %}

{% block content %}

    <h1> Create student </h1>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>

{% endblock content %}

learn_django/otusPlus/templates/otusPlus/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Обучение в ОТУСе</title>
</head>
<body>
<div>
    <h1>Привет всем!</h1>

    <h3>Все занятия:</h3>
    <div>
        <ul>
            {% for lesson in all_lessons %}
            <ul>
                <li>
                    <div>Время урока: {{ lesson.date_time_of_lesson }}</div>
                    <div>Тема урока: {{ lesson.theme_of_lesson }}</div>
                    <div>Курс: {{ lesson.course }}</div>
                    <div>Преподаватель: {{ lesson.teacher }}</div>
                </li>
            </ul>
            {% endfor %}
        </ul>
    </div>
    <hr>
    <h3>Ближайшие занятия:</h3>
    <div>
        <ul>
            {% for lesson in hot_lessons %}
            <ul>
                <li>
                    <div>Время урока: {{ lesson.date_time_of_lesson }}</div>
                    <div>Тема урока: {{ lesson.theme_of_lesson }}</div>
                    <div>Курс: {{ lesson.course }}</div>
                    <div>Преподаватель: {{ lesson.teacher }}</div>
                </li>
            </ul>
            {% endfor %}
        </ul>
    </div>
    <hr>
    <h3>Все документы курса:</h3>
    <ul>
        {% for document in all_docs %}
            <li>
                <div>
                    <b>Название документа:</b> {{ document.title }}
                </div>
                <div>
                    Тип вида документа: {{ document.get_type_of_doc_display }}
                </div>
<!--                <div>-->
<!--                    <ul>-->
<!--                        {% for key, value in document.TYPE_OF_DOC %}-->
<!--                        <li>{{ key }} : {{ value }}</li>-->
<!--                        {% endfor %}-->
<!--                    </ul>-->
<!--                </div>-->
                <div>
                    Автор: {{ document.author }}
                </div>
            </li>
        {% endfor %}
    </ul>
    <hr>
    <h3>Все студенты:</h3>
    <ul>
        {% for student in all_students %}
        <li>
            <div>
                Студент: {{ student.full_name }}
            </div>
            <div>
                Email студента: {{ student.email }}
            </div>
        </li>
        {% endfor %}
    </ul>
    <hr>
    <h3>Все курсы:</h3>
    <ul>
        {% for course in all_courses %}
        <li>
            <div>
                Наименование курса: {{ course.title }}
            </div>
                <div>Преподаватель: {{ course.teacher }}</div>
            <div>
                Студент:
                <ul>
                    {% for student in course.students.all %}
                    <li>
                        Имя студента: {{ student.full_name }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </li>

        {% endfor %}
    </ul>
    <hr>
    <div>
        <h3>URL страницы</h3>
         <div>
            This page url: {% url 'otusPlus:index' %}
        </div>
    </div>
</div>
</body>
</html>